name: CMake Multi-Project CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: actions/setup-cmake@v3

      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build-type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure