name: linux

on: [push, pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Debug, Release]
        cxx: [g++-13, g++-14, clang++-17, clang++-18]
    
    env:
      CXX: ${{ matrix.cxx }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ninja
        run: sudo apt-get install ninja-build

      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build-type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure
